//request list of pokemons
export const START_FETCH_POKEMONS = "START_FETCH_POKEMONS";
export const SUCCESS_FETCH_POKEMONS = "SUCCESS_FETCH_POKEMONS";
export const FAIL_FETCH_POKEMONS = "FAIL_FETCH_POKEMONS";

//request pokemones types
export const START_FETCH_POKEMONS_TYPES = "START_FETCH_POKEMONS_TYPES";
export const SUCCESS_FETCH_POKEMONS_TYPES = "SUCCESS_FETCH_POKEMONS_TYPES";
export const FAIL_FETCH_POKEMONS_TYPES = "FAIL_FETCH_POKEMONS_TYPES";

//request pokemones by type
export const START_FETCH_POKEMONS_BY_TYPE = "START_FETCH_POKEMONS_BY_TYPE";
export const SUCCESS_FETCH_POKEMONS_BY_TYPE = "SUCCESS_FETCH_POKEMONS_BY_TYPE";
export const FAIL_FETCH_POKEMONS_BY_TYPE = "FAIL_FETCH_POKEMONS_BY_TYPE";

//request pokemon profile
export const START_FETCH_POKEMON_PROFILE = "START_FETCH_POKEMON_PROFILE";
export const SUCCESS_FETCH_POKEMON_PROFILE = "SUCCESS_FETCH_POKEMON_PROFILE";
export const FAIL_FETCH_POKEMON_PROFILE = "FAIL_FETCH_POKEMON_PROFILE";
